apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: ${{ secrets.OCEAN_AUTHORITY}}
      server: https://b66fa29e-52ca-4a24-9ee6-d0c658b9efff.k8s.ondigitalocean.com
    name: do-ams3-tempus-reality
contexts:
  - context:
      cluster: do-ams3-tempus-reality
      user: do-ams3-tempus-reality-admin
    name: do-ams3-tempus-reality
current-context: do-ams3-tempus-reality
kind: Config
preferences: {}
users:
  - name: do-ams3-tempus-reality-admin
    user:
      token: ${{ secrets.DIGITALOCEAN_TOKEN}}
