apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-api
  labels:
    app: a-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a-api
  template:
    metadata:
      labels:
        app: a-api
    spec:
      containers:
        - name: a-api
          image: iryvern/auth_api:latest
          ports:
            - containerPort: 8080
